name: Build Flet Mobile App

on:
  workflow_dispatch: # 允许手动点击按钮触发打包

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install Dependencies
        run: |
          pip install flet

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-word-app-apk
          path: build/apk/*.apk
